import pyscord
import random
import discord

bot = pyscord.Client(token="ODc3NTY4Njc0NjY2NTI0Njgy.YR0hhA.qahcocZ66Ic7dQk8mgXLvwt4kK8")
guilds = bot.getguilds()
guild = guilds.getguild(804096311975477279)
print(guild.id)
print(guild.name)
print(guild.icon)
print(guild.owner)
print(guild.permissions)
print(guild.features)
preview = bot.getpreview(804096311975477279)
print(preview.id)
print(preview.name)
print(preview.icon)
print(preview.description)
print(preview.splash)
print(preview.discovery_splash)
print(preview.features)
print(preview.approximate_member_count)
print(preview.approximate_presence_count)
print(preview.emojis)
print(guild, preview)